export const translations={
    en: {
        translation: {
          emailLabel: "Email",
          passwordLabel: "Password",
          emailError: "Email is required.",
          invalidEmail: "Invalid email address. E.g. example@email.com",
          passwordError: "Password is required.",
          signIn: "Sign In",
          rememberMe: "Remember me",
          forgotPassword: "Forgot Password?",
          dontHaveAccount: "Don't have an account?",
          signUp: "Sign Up",
          signInHeading: "Sign In",
          signInSubHeading: "Enter your credentials to continue",
          testCenter: "Test Center",
          studentPortal: "Student Portal",
          teachers: "Teachers",
          analysis: "Analysis",
          admission: "Admission",
          imageAltText: "Image",
          namePlaceholder: "John Doe",
          postPlaceholder: "School Manager",
          welcomeMessage: "Welcome back,",
          schoolNamePlaceholder: "Ryan International School, Rohini",
          schoolIDPlaceholder: "School ID: 345677",
          schoolAddressPlaceholder: "22 Clarington Street, Haryana, UP 201090",
          schoolPhoneNumber: "+91-8888-888-888",
          firstNameRequired: "First name is required.",
          lastNameRequired: "Last name is required.",
          emailRequired: "Email is required.",
          passwordRequired: "Password is required.",
          passwordSuggestions: "Suggestions",
          passwordLowerCase: "At least one lowercase",
          passwordUpperCase: "At least one uppercase",
          passwordNumeric: "At least one numeric",
          passwordLength: "Minimum 8 characters",
          signUpHeading: "Sign Up",
          enterCredentials: "Enter your credentials to continue",
          firstName: "First Name",
          lastName: "Last Name",
          email: "Email",
          password: "Password",
          alreadyHaveAccount: "Already have an account?",
          home: "Home",
          settings: "Settings",
          QuickLink: "Quick Link",
          CreateTest: "create test",
          AddStudent: "add students",
          AddQuestion: "add question"
        },
      },
      hi: {
        translation: {
          emailLabel: "ईमेल",
          passwordLabel: "पासवर्ड",
          emailError: "ईमेल आवश्यक है।",
          invalidEmail: "अमान्य ईमेल पता। उदाहरण: example@email.com",
          passwordError: "पासवर्ड आवश्यक है।",
          signIn: "साइन इन करें",
          rememberMe: "मुझे याद रखें",
          forgotPassword: "पासवर्ड भूल गए?",
          dontHaveAccount: "खाता नहीं है?",
          signUp: "साइन अप करें",
          signInHeading: "साइन इन करें",
          signInSubHeading: "जारी रखने के लिए अपना खाता साइन इन करें",
          testCenter: "टेस्ट सेंटर",
          studentPortal: "छात्र पोर्टल",
          teachers: "शिक्षक",
          analysis: "विश्लेषण",
          admission: "प्रवेश",
          imageAltText: "छवि",
          namePlaceholder: "जॉन डो",
          postPlaceholder: "स्कूल प्रबंधक",
          welcomeMessage: "वापस स्वागत है,",
          schoolNamePlaceholder: "रायन इंटरनेशनल स्कूल, रोहिणी",
          schoolIDPlaceholder: "स्कूल आईडी: 345677",
          schoolAddressPlaceholder:
            "22 क्लारिंग्टन स्ट्रीट, हरियाणा, यूपी 201090",
          schoolPhoneNumber: "+91-8888-888-888",
          firstNameRequired: "पहला नाम आवश्यक है।",
          lastNameRequired: "अंतिम नाम आवश्यक है।",
          emailRequired: "ईमेल आवश्यक है।",
          passwordRequired: "पासवर्ड आवश्यक है।",
          passwordSuggestions: "सुझाव",
          passwordLowerCase: "कम से कम एक छोटा अक्षर",
          passwordUpperCase: "कम से कम एक बड़ा अक्षर",
          passwordNumeric: "कम से कम एक संख्यात्मक",
          passwordLength: "कम से कम 8 अक्षर",
          signUpHeading: "साइन अप",
          enterCredentials: "जारी रखने के लिए अपना साक्षरता दर्ज करें",
          firstName: "पहला नाम",
          lastName: "अंतिम नाम",
          email: "ईमेल",
          password: "पासवर्ड",
          alreadyHaveAccount: "पहले से ही खाता है?",
          home: "होम",
          settings: "सेटिंग्स",
          QuickLink  : "त्वरित लिंक"
        },
      },
}